// <auto-generated />
namespace DoctorsAppoinmentMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addDoctorAndDepartment2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDoctorAndDepartment2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181718229_addDoctorAndDepartment2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
